### ISSUE TITLE
Log Button

### ISSUE THREAD

**Issue by Mailaender** [jenkinsci/remote-result-trigger-plugin#6]
### What feature do you want to see added?

A button at job level that shows logging of the polling action. I can't get this plugin to work and I also can't find any logs written on the Jenkins machine, so I can't debug why it is broken. [URLTrigger](https://github.com/jenkinsci/urltrigger-plugin) has a convenient Log button.

### Upstream changes

None

**Comment by itfsw** [comment]
has added
